In [1]:
#Dependencies
import pandas as pd

In [ ]:
#READ IN CSVs

In [26]:
#Set year
year = "2020"

#list of months
months = ["01", "02", "03", "04", "05", "06", "07"]

#Create empty df
df_20 = pd.DataFrame()

#Loop through months to sample and append to df
for month in months:
    temp_df = pd.read_csv(f'../Resources/{year}_rides/{year}{month}-citibike-tripdata.csv')
    temp_df = temp_df.sample(frac=.1, random_state = 88)
    df_20 = df_20.append(temp_df)
    
    print(month)

01
02
03
04
05
06
07

In [27]:
df_20.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
483494,1321,2020-01-13 07:23:45.8130,2020-01-13 07:45:47.3080,317,E 6 St & Avenue B,40.724537,-73.981854,379,W 31 St & 7 Ave,40.749156,-73.991600,38532,Subscriber,1978,1
805298,624,2020-01-21 20:33:58.6200,2020-01-21 20:44:23.2490,540,Lexington Ave & E 29 St,40.743116,-73.982154,334,W 20 St & 7 Ave,40.742388,-73.997262,33993,Customer,1969,0
932353,596,2020-01-24 16:37:13.8450,2020-01-24 16:47:10.2820,3409,Bergen St & Smith St,40.686744,-73.990632,3429,Hanson Pl & Ashland Pl,40.685068,-73.977908,38365,Subscriber,1990,2
986003,152,2020-01-26 14:04:41.3430,2020-01-26 14:07:14.1300,3132,E 59 St & Madison Ave,40.763505,-73.971092,305,E 58 St & 3 Ave,40.760958,-73.967245,35230,Subscriber,1968,1
249096,780,2020-01-08 09:08:32.4290,2020-01-08 09:21:32.4320,3555,28 St & 41 Ave,40.751047,-73.937970,385,E 55 St & 2 Ave,40.757973,-73.966033,33145,Subscriber,1985,1

In [28]:
len(df_20)

961462

In [29]:
#write new csv
#df_20.to_csv('../Resources/rides_20.csv')

In [30]:
#Repeat for 2019

In [31]:
#Set year
year = "2019"

#list of months
months = ["01", "02", "03", "04", "05", "06", "07"]

#Create empty df
df_19 = pd.DataFrame()

#Loop through months to sample and append to df
for month in months:
    temp_df = pd.read_csv(f'../Resources/{year}_rides/{year}{month}-citibike-tripdata.csv')
    temp_df = temp_df.sample(frac=.1, random_state = 88)
    df_19 = df_19.append(temp_df)
    
    print(month)

01
02
03
04
05
06
07

In [32]:
df_19.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
743133,271,2019-01-24 07:05:59.8800,2019-01-24 07:10:31.0550,490.0,8 Ave & W 33 St,40.751551,-73.993934,529.0,W 42 St & 8 Ave,40.757570,-73.990985,30433,Subscriber,1963,1
33663,445,2019-01-02 10:41:37.1980,2019-01-02 10:49:02.8820,2009.0,Catherine St & Monroe St,40.711174,-73.996826,377.0,6 Ave & Canal St,40.722438,-74.005664,18081,Subscriber,1992,1
471817,1670,2019-01-15 06:12:51.3110,2019-01-15 06:40:41.3140,3541.0,Amsterdam Ave & W 125 St,40.813358,-73.956461,3557.0,40 Ave & 9 St,40.757420,-73.945133,35652,Subscriber,1984,2
816706,1760,2019-01-26 15:44:45.0630,2019-01-26 16:14:05.8880,244.0,Willoughby Ave & Hall St,40.691960,-73.965369,3232.0,Bond St & Fulton St,40.689622,-73.983043,35682,Subscriber,1968,2
880904,561,2019-01-28 17:29:57.2580,2019-01-28 17:39:18.6980,3110.0,Meserole Ave & Manhattan Ave,40.727086,-73.952991,3453.0,Devoe St & Lorimer St,40.713352,-73.949103,33954,Subscriber,1994,1

In [33]:
len(df_19)

1123607

In [34]:
#write new csv
#df_19.to_csv('../Resources/rides_19.csv')

In [37]:
#Create merged df
df = pd.DataFrame()
df = df.append([df_19, df_20])

In [38]:
df.to_csv('../Resources/rides_19-20.csv')

In [40]:
len(df)

2085069

In [41]:
df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
743133,271,2019-01-24 07:05:59.8800,2019-01-24 07:10:31.0550,490.0,8 Ave & W 33 St,40.751551,-73.993934,529.0,W 42 St & 8 Ave,40.757570,-73.990985,30433,Subscriber,1963,1
33663,445,2019-01-02 10:41:37.1980,2019-01-02 10:49:02.8820,2009.0,Catherine St & Monroe St,40.711174,-73.996826,377.0,6 Ave & Canal St,40.722438,-74.005664,18081,Subscriber,1992,1
471817,1670,2019-01-15 06:12:51.3110,2019-01-15 06:40:41.3140,3541.0,Amsterdam Ave & W 125 St,40.813358,-73.956461,3557.0,40 Ave & 9 St,40.757420,-73.945133,35652,Subscriber,1984,2
816706,1760,2019-01-26 15:44:45.0630,2019-01-26 16:14:05.8880,244.0,Willoughby Ave & Hall St,40.691960,-73.965369,3232.0,Bond St & Fulton St,40.689622,-73.983043,35682,Subscriber,1968,2
880904,561,2019-01-28 17:29:57.2580,2019-01-28 17:39:18.6980,3110.0,Meserole Ave & Manhattan Ave,40.727086,-73.952991,3453.0,Devoe St & Lorimer St,40.713352,-73.949103,33954,Subscriber,1994,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
736591,106,2020-07-12 18:08:21.2380,2020-07-12 18:10:07.2730,3320.0,Central Park West & W 100 St,40.794067,-73.962868,3320.0,Central Park West & W 100 St,40.794067,-73.962868,27059,Customer,1986,2
1103952,836,2020-07-17 17:36:55.8540,2020-07-17 17:50:52.2750,519.0,Pershing Square North,40.751873,-73.977706,3708.0,W 13 St & 5 Ave,40.735445,-73.994310,14577,Subscriber,1954,1
1004272,309,2020-07-16 12:11:59.8970,2020-07-16 12:17:09.8650,473.0,Rivington St & Chrystie St,40.721101,-73.991925,350.0,Clinton St & Grand St,40.715595,-73.987030,19037,Subscriber,1992,1
236092,1422,2020-07-04 16:32:01.0620,2020-07-04 16:55:43.9930,3016.0,Kent Ave & N 7 St,40.720368,-73.961651,3062.0,Myrtle Ave & Marcy Ave,40.695398,-73.949549,44217,Customer,1992,2
1233648,1702,2020-07-19 12:48:15.0950,2020-07-19 13:16:37.1590,3301.0,Columbus Ave & W 95 St,40.791956,-73.968087,3259.0,9 Ave & W 28 St,40.749370,-73.999234,30038,Subscriber,1980,1